spring:
    main:
        allow-circular-references: true
    application:
        name: DrugsApp
    data:
        jpa.repositories.enabled: true
    datasource:
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/drugs_db
        username:
        password:
        continueOnError: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: true
            generate-ddl: true
        properties:
            hibernate:
                jdbc.lob.non_contextual_creation: true
                show_sql: false
                format_sql: false
                generate_statistics: true
                jdbc:
                    batch_size: 100
                order_inserts: true
                dialect: org.hibernate.dialect.PostgreSQLDialect